### ISSUE TITLE
glibc.db.xz having a mismatched hash

### ISSUE THREAD

**Issue by sin3point14** [0xb0bb/karkinos#3]
Running `./kark.py --help` gives this-

```bash
❯ ./kark.py --help
downloading: https://raw.githubusercontent.com/0xb0bb/karkinos/master/db/libs.json (186b)
extracting:  glibc.db.xz
error: glibc.db.xz failed; mismatched hash
usage: kark.py [-h] [--libdb {glibc,libstdc++}] [--distro DISTRO]
               [--arch {x86,amd64,i386,arm,arm64,mips,mips64,ppc,ppc64,sparc,sparc64,m68k,hppa,sh4}]
               [--endian {little,big}]
               {find,dump,info,update,version} ...
```

All other commands give the same error

**Comment by 0xb0bb** [comment]
Could you please tell me what version you are using:

```
$ ./kark.py version
Version: Karkinos v0.5
Author:  b0bb
Contact: https://twitter.com/0xb0bb
Project: https://github.com/0xb0bb/karkinos
```
I have been making small changes here and there as I add more libs and a better update system (as well as pypi package), so there may be incompatibilities. I plan to have all these changes sorted by the end of the week.

A quick fix (assuming you are using the latest version) would be to delete everything in `/db/` and it will download the latest library dbs on the next run (which should be about `~70mb`.

I will attempt to make this clearer in the error message.
